/* Modelo_Logico_FelipeFreitas_LuizaHeller: */

CREATE TABLE Carro (
    Codigo INTEGER UNSIGNED NOT NULL PRIMARY KEY,
    Placa CHAR(7) NOT NULL,
    Marca VARCHAR(40) NOT NULL,
    Modelo VARCHAR(50) NOT NULL,
    Ano SMALLINT(4) UNSIGNED NOT NULL,
    Nome_Motorista VARCHAR(100) NOT NULL,
    UNIQUE (Placa, Codigo)
);

CREATE TABLE Passageiro (
    CPF CHAR(11) NOT NULL PRIMARY KEY UNIQUE,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(110) NOT NULL,
    Telefone VARCHAR(13) NOT NULL,
    Bairro VARCHAR(255),
    Cidade VARCHAR(255),
    Estado VARCHAR(20),
    Meio_Pagamento VARCHAR(20)
);

CREATE TABLE Viagem (
    Id INTEGER UNSIGNED NOT NULL PRIMARY KEY UNIQUE,
    Kms DECIMAL(6,2)  UNSIGNED NOT NULL,
    Valor DECIMAL(6,2) UNSIGNED NOT NULL,
    Duracao INTEGER(4) UNSIGNED NOT NULL,
    FK_Carro_Codigo INTEGER UNSIGNED NOT NULL
);

CREATE TABLE Urbana (
    Bairro_Partida VARCHAR(255) NOT NULL,
    Bairro_Destino VARCHAR(255) NOT NULL,
    FK_Viagem_Id INTEGER UNSIGNED NOT NULL PRIMARY KEY
);

CREATE TABLE Interurbana (
    Taxa_Adicional DECIMAL(6,2),
    Cidade_Partida VARCHAR(255),
    Cidade_Destino VARCHAR(255) NOT NULL,
    FK_Viagem_Id INTEGER UNSIGNED NOT NULL PRIMARY KEY
);

CREATE TABLE Usa (
    FK_Passageiro_CPF CHAR(11) NOT NULL,
    FK_Viagem_Id INTEGER UNSIGNED NOT NULL UNIQUE
);
 
ALTER TABLE Viagem ADD CONSTRAINT FK_Viagem_1
    FOREIGN KEY (FK_Carro_Codigo)
    REFERENCES Carro (Codigo)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Urbana ADD CONSTRAINT FK_Urbana_1
    FOREIGN KEY (FK_Viagem_Id)
    REFERENCES Viagem (Id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Interurbana ADD CONSTRAINT FK_Interurbana_0
    FOREIGN KEY (FK_Viagem_Id)
    REFERENCES Viagem (Id)
    ON DELETE CASCADE ON UPDATE CASCADE;
 
ALTER TABLE Usa ADD CONSTRAINT FK_Usa_0
    FOREIGN KEY (FK_Passageiro_CPF)
    REFERENCES Passageiro (CPF)
    ON DELETE RESTRICT ON UPDATE RESTRICT;
 
ALTER TABLE Usa ADD CONSTRAINT FK_Usa_1
    FOREIGN KEY (FK_Viagem_Id)
    REFERENCES Viagem (Id)
    /*ON DELETE SET NULL */ON UPDATE CASCADE;