SELECT C.CODIGO
FROM CARRO C
INNER JOIN VIAGEM V ON C.CODIGO = V.FK_CARRO_CODIGO
INNER JOIN URBANA U ON U.FK_VIAGEM_ID = V.ID
WHERE U.BAIRRO_PARTIDA = 'Floresta';

SELECT P.NOME, C.CODIGO
FROM PASSAGEIRO P
INNER JOIN USA ON USA.FK_PASSAGEIRO_CPF = P.CPF
INNER JOIN VIAGEM V ON V.ID = USA.FK_VIAGEM_ID
INNER JOIN CARRO C ON C.CODIGO = V.FK_CARRO_CODIGO
INNER JOIN URBANA U ON U.FK_VIAGEM_ID = V.ID
WHERE P.BAIRRO = U.BAIRRO_PARTIDA;

SELECT P.CPF, P.NOME, SUM(V.KMS)
FROM PASSAGEIRO P
INNER JOIN USA ON USA.FK_PASSAGEIRO_CPF = P.CPF
INNER JOIN VIAGEM V ON V.ID = USA.FK_VIAGEM_ID
GROUP BY P.CPF, P.NOME;
